# This file contains custom mapping, which cannot be resolved by:
# - reading object property names and
# - converting them to camel_case

App\SuperMetrics\TokenResponseData:
    attributes:
        token:
            serialized_name: sl_token

App\SuperMetrics\GetPostsRequest:
    attributes:
        token:
            serialized_name: sl_token

App\Provider\Post:
    attributes:
        authorName:
            serialized_name: from_name
        authorId:
            serialized_name: from_id
        createdTime:
